export interface GenreCategory {
  id: string;
  label: string;
  icon: string;
}

export interface GenreSource {
  type: "rss" | "reddit" | "youtube";
  url: string;
  name: string;
}

export interface Genre {
  id: string;
  name: string;
  icon: string;
  description: string;
  categories: GenreCategory[];
  sources: GenreSource[];
  contentPrompt: string;
  voiceTone: string;
  categorizationPrompt: string;
}

export const GENRES: Record<string, Genre> = {
  ai: {
    id: "ai",
    name: "AI & Dev",
    icon: "Brain",
    description: "Emerging AI models, agents, dev tools, standards, and research",
    categories: [
      { id: "models", label: "Models", icon: "Brain" },
      { id: "agents", label: "Agents", icon: "Bot" },
      { id: "tooling", label: "Tooling", icon: "Wrench" },
      { id: "standards", label: "Standards", icon: "FileCode" },
      { id: "research", label: "Research", icon: "FlaskConical" },
      { id: "safety", label: "Safety", icon: "Shield" },
      { id: "startups", label: "Startups", icon: "Rocket" },
      { id: "infra", label: "Infra", icon: "Server" },
    ],
    sources: [
      // Frontier labs & platforms
      { type: "rss", url: "https://openai.com/news/rss.xml", name: "OpenAI" },
      { type: "rss", url: "https://deepmind.google/blog/rss.xml", name: "Google DeepMind" },
      { type: "rss", url: "https://huggingface.co/blog/feed.xml", name: "Hugging Face" },
      { type: "rss", url: "https://github.blog/feed/", name: "GitHub Blog" },
      { type: "rss", url: "https://blog.research.google/feeds/posts/default", name: "Google Research" },
      { type: "rss", url: "https://bair.berkeley.edu/blog/feed.xml", name: "BAIR" },
      // Fast-moving news / Show HN (great for first-sightings)
      { type: "rss", url: "https://hnrss.org/frontpage?points=100", name: "Hacker News" },
      { type: "rss", url: "https://hnrss.org/show", name: "Show HN" },
      { type: "rss", url: "https://hnrss.org/newest?q=AI+OR+LLM+OR+agent", name: "HN New (AI)" },
      // arXiv (new techniques, benchmarks)
      { type: "rss", url: "http://export.arxiv.org/rss/cs.AI", name: "arXiv cs.AI" },
      { type: "rss", url: "http://export.arxiv.org/rss/cs.CL", name: "arXiv cs.CL" },
      { type: "rss", url: "http://export.arxiv.org/rss/cs.LG", name: "arXiv cs.LG" },
      // Tech press (AI verticals)
      { type: "rss", url: "https://techcrunch.com/category/artificial-intelligence/feed/", name: "TechCrunch AI" },
      { type: "rss", url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml", name: "The Verge AI" },
      { type: "rss", url: "https://arstechnica.com/ai/feed/", name: "Ars Technica AI" },
      { type: "rss", url: "https://venturebeat.com/category/ai/feed/", name: "VentureBeat AI" },
      { type: "rss", url: "https://www.technologyreview.com/topic/artificial-intelligence/feed", name: "MIT Tech Review AI" },
      // Practitioner blogs / newsletters (earliest signal on new conventions)
      { type: "rss", url: "https://simonwillison.net/atom/everything/", name: "Simon Willison" },
      { type: "rss", url: "https://www.latent.space/feed", name: "Latent Space" },
      { type: "rss", url: "https://jack-clark.net/feed/", name: "Import AI" },
      { type: "rss", url: "https://www.deeplearning.ai/the-batch/feed/", name: "The Batch" },
      { type: "rss", url: "https://www.semianalysis.com/feed", name: "SemiAnalysis" },
      // Reddit
      { type: "reddit", url: "LocalLLaMA", name: "r/LocalLLaMA" },
      { type: "reddit", url: "MachineLearning", name: "r/MachineLearning" },
      { type: "reddit", url: "artificial", name: "r/artificial" },
      { type: "reddit", url: "OpenAI", name: "r/OpenAI" },
      { type: "reddit", url: "singularity", name: "r/singularity" },
      // YouTube
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCbfYPyITQ-7l4upoX8nvctg", name: "Two Minute Papers" },
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZHmQk67mSJgfCCTn7xBfew", name: "Yannic Kilcher" },
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCNJ1Ymd5yFuUPtn21xtRbbw", name: "AI Explained" },
    ],
    contentPrompt: "sharp, technical-but-accessible, explains why a new thing matters and who should care",
    voiceTone: "Informed, early-adopter, no hype, signal over noise",
    categorizationPrompt:
      "Focus on genuinely new or fast-rising things developers and founders should know about. Categories: models (new LLMs/frontier model releases), agents (AI agents, agentic frameworks, MCP, agents.md), tooling (dev tools, SDKs, frameworks, IDEs), standards (new specs/conventions like agents.md, llms.txt, MCP), research (papers, benchmarks, techniques), safety (alignment, policy, regulation), startups (funding, launches, company moves), infra (compute, GPUs, serving, deployment).",
  },

  paranormal: {
    id: "paranormal",
    name: "Paranormal & Mystery",
    icon: "Ghost",
    description: "UFOs, ghosts, true crime, cryptids, and unexplained phenomena",
    categories: [
      { id: "ufo", label: "UFO", icon: "TrendingUp" },
      { id: "paranormal", label: "Paranormal", icon: "Ghost" },
      { id: "cryptid", label: "Cryptid", icon: "Footprints" },
      { id: "conspiracy", label: "Conspiracy", icon: "Eye" },
      { id: "true_crime", label: "True Crime", icon: "Skull" },
      { id: "unresolved", label: "Unresolved", icon: "HelpCircle" },
      { id: "weird_news", label: "Weird News", icon: "Newspaper" },
    ],
    sources: [
      { type: "reddit", url: "UFOs", name: "r/UFOs" },
      { type: "reddit", url: "Paranormal", name: "r/Paranormal" },
      { type: "reddit", url: "UnresolvedMysteries", name: "r/UnresolvedMysteries" },
      { type: "rss", url: "https://www.coasttocoastam.com/rss/weird-news/", name: "Coast to Coast AM" },
      { type: "rss", url: "https://www.mirror.co.uk/news/weird-news/rss.xml", name: "Mirror Weird News" },
      { type: "rss", url: "https://www.thesun.co.uk/topic/weird-news/feed/", name: "The Sun Weird News" },
      { type: "rss", url: "https://www.express.co.uk/posts/rss/80/weird", name: "Express Weird" },
      { type: "rss", url: "https://www.dailystar.co.uk/news/weird-news/rss", name: "Daily Star Weird" },
      { type: "rss", url: "https://feeds.bbci.co.uk/news/science_and_environment/rss.xml", name: "BBC Science" },
      { type: "rss", url: "https://www.space.com/feeds/all", name: "Space.com" },
      { type: "rss", url: "https://www.livescience.com/feeds/all", name: "Live Science" },
      { type: "rss", url: "https://www.sciencedaily.com/rss/strange_offbeat.xml", name: "Science Daily Strange" },
      { type: "rss", url: "https://phys.org/rss-feed/space-news/", name: "Phys.org Space" },
      { type: "rss", url: "https://openminds.tv/feed/", name: "Open Minds UFO" },
      { type: "rss", url: "https://www.latest-ufo-sightings.net/feed/atom", name: "Latest UFO Sightings" },
      { type: "rss", url: "https://www.theblackvault.com/casefiles/feed/", name: "The Black Vault" },
      { type: "rss", url: "https://www.earthfiles.com/feed/", name: "Earthfiles" },
      { type: "rss", url: "https://feeds.feedburner.com/TheUFOChronicles", name: "The UFO Chronicles" },
      { type: "rss", url: "https://www.cbsnews.com/latest/rss/48-hours", name: "48 Hours" },
      { type: "rss", url: "https://feeds.megaphone.fm/casefile", name: "Casefile" },
      { type: "rss", url: "https://rss.art19.com/crime-junkie", name: "Crime Junkie" },
      { type: "rss", url: "https://defrostingcoldcases.com/feed/", name: "Defrosting Cold Cases" },
      { type: "rss", url: "https://truecrimesocietyblog.com/feed/", name: "True Crime Society" },
      { type: "rss", url: "https://forensicfilesnow.com/index.php/feed/", name: "Forensic Files" },
      { type: "rss", url: "https://www.oddmurdersandmysteries.com/feed/", name: "Odd Murders" },
      { type: "rss", url: "https://www.truecasefiles.com/feeds/posts/default?alt=rss", name: "True Case Files" },
      { type: "rss", url: "https://mysteriousuniverse.org/feed/", name: "Mysterious Universe" },
      { type: "rss", url: "https://www.phantomsandmonsters.com/feeds/posts/default?alt=rss", name: "Phantoms and Monsters" },
      { type: "rss", url: "https://www.thefortean.com/feed/", name: "The Fortean" },
      { type: "rss", url: "https://www.ancient-origins.net/rss.xml", name: "Ancient Origins" },
      { type: "rss", url: "https://www.ancient-code.com/feed/", name: "Ancient Code" },
      { type: "rss", url: "https://cryptomundo.com/feed/", name: "Cryptomundo" },
      { type: "rss", url: "https://www.strangeanimals.info/feeds/posts/default?alt=rss", name: "Strange Animals" },
      { type: "rss", url: "https://sasquatchchronicles.com/feed/", name: "Sasquatch Chronicles" },
      { type: "rss", url: "https://sharonahill.com/feed/", name: "Sharon Hill" },
      { type: "rss", url: "http://kevinrandle.blogspot.com/feeds/posts/default", name: "Kevin Randle" },
      { type: "rss", url: "https://www.bfro.net/gdb/rss.asp", name: "BFRO" },
      { type: "rss", url: "https://ghostvillage.com/feed/", name: "Ghost Village" },
      { type: "rss", url: "https://thedeadhistory.com/feed/", name: "The Dead History" },
      { type: "rss", url: "https://www.theparacast.com/feed/", name: "The Paracast" },
      { type: "rss", url: "https://jimharold.com/feed/", name: "Jim Harold" },
      { type: "rss", url: "https://www.ufosightingsdaily.com/feeds/posts/default?alt=rss", name: "UFO Sightings Daily" },
      { type: "rss", url: "https://www.ufo-blogger.com/feeds/posts/default?alt=rss", name: "UFO Blogger" },
      { type: "rss", url: "https://podcast.earthfiles.com/feed/", name: "Earthfiles Podcast" },
      { type: "rss", url: "https://www.trailwentcold.com/feed/", name: "The Trail Went Cold" },
      { type: "rss", url: "https://coldcasecanada.podbean.com/feed.xml", name: "Cold Case Canada" },
      { type: "rss", url: "https://weekinweird.com/feed/", name: "Week in Weird" },
      { type: "rss", url: "https://www.npr.org/rss/rss.php?id=1008", name: "NPR Culture" },
      { type: "rss", url: "https://tetzoo.com/podcast?format=rss", name: "TetZoo" },
      { type: "rss", url: "https://www.atlasobscura.com/feeds/latest", name: "Atlas Obscura" },
      { type: "rss", url: "https://boingboing.net/feed", name: "Boing Boing" },
      { type: "rss", url: "https://www.odditycentral.com/feed", name: "Oddity Central" },
      { type: "rss", url: "https://www.mentalfloss.com/feed", name: "Mental Floss" },
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCuHn_E6xPuhI_jiOvQXaVIg", name: "The Black Vault" },
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCvSbzThCfsiETLp3eOdVkNw", name: "That UFO Podcast" },
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZo6c5e3u_K96vP8z5b0eWg", name: "Jeremy Corbell" },
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC6qRJj0aAxwLhIGMsAdUf_A", name: "Richard Dolan" },
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCJkUnypo-HJs0Q_FzYJZYfQ", name: "Project Unity" },
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCPaRG_5YlBnKnL4Rj5LGJEg", name: "MUFON" },
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UC7WMgAJFGFqNQP-5LbPE7FA", name: "The Why Files" },
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCBhQ1zXgVXNWQy46_v8caCA", name: "Stuff They Don't Want You To Know" },
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCtPrkXdtCM5DACLufB9jbsA", name: "MrBallen" },
      { type: "youtube", url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCBnbnH-uK3b6K1SdoMY8aGQ", name: "Nuke's Top 5" },
    ],
    contentPrompt: "mystery/investigative/suspenseful tone",
    voiceTone: "Curious, building tension, respectful of the unknown",
    categorizationPrompt:
      "Only categorise if the story is clearly paranormal or mystery related. Use the most specific category that fits: ufo (sightings, UAP, aliens), paranormal (ghosts, hauntings), cryptid (Bigfoot, Nessie, unknown creatures), conspiracy (coverups, secret societies), true_crime (murders, investigations), unresolved (cold cases, disappearances), weird_news (strange but doesn't fit above). Do not categorise routine news, sports, or unrelated topics.",
  },

  tech: {
    id: "tech",
    name: "Tech",
    icon: "Cpu",
    description: "AI, startups, cybersecurity, gadgets, and science",
    categories: [
      { id: "ai", label: "AI", icon: "Brain" },
      { id: "startups", label: "Startups", icon: "Rocket" },
      { id: "cybersecurity", label: "Cybersecurity", icon: "Shield" },
      { id: "gadgets", label: "Gadgets", icon: "Smartphone" },
      { id: "science", label: "Science", icon: "FlaskConical" },
      { id: "crypto", label: "Crypto", icon: "Coins" },
    ],
    sources: [
      { type: "rss", url: "https://techcrunch.com/feed/", name: "TechCrunch" },
      { type: "rss", url: "https://techcrunch.com/startups/feed/", name: "TechCrunch Startups" },
      { type: "rss", url: "https://www.theverge.com/rss/index.xml", name: "The Verge" },
      { type: "rss", url: "https://www.theverge.com/rss/tech/index.xml", name: "The Verge Tech" },
      { type: "rss", url: "https://www.theverge.com/rss/cyber-security/index.xml", name: "The Verge Security" },
      { type: "rss", url: "https://feeds.arstechnica.com/arstechnica/index", name: "Ars Technica" },
      { type: "rss", url: "https://www.wired.com/feed/rss", name: "Wired" },
      { type: "rss", url: "https://www.engadget.com/rss.xml", name: "Engadget" },
      { type: "rss", url: "https://venturebeat.com/feed/", name: "VentureBeat" },
      { type: "rss", url: "https://thenextweb.com/feed/", name: "The Next Web" },
      { type: "rss", url: "https://www.zdnet.com/news/rss.xml", name: "ZDNet" },
      { type: "rss", url: "https://gizmodo.com/rss", name: "Gizmodo" },
      { type: "rss", url: "https://www.techradar.com/rss", name: "TechRadar" },
      { type: "rss", url: "https://www.technologyreview.com/feed/", name: "MIT Tech Review" },
      { type: "rss", url: "https://feeds.feedburner.com/fastcompany/headlines", name: "Fast Company" },
      { type: "rss", url: "https://www.newscientist.com/feed/home/", name: "New Scientist" },
      { type: "rss", url: "https://phys.org/rss-feed/", name: "Phys.org" },
      { type: "rss", url: "https://www.sciencedaily.com/rss/all.xml", name: "Science Daily" },
      { type: "rss", url: "https://news.mit.edu/rss/research", name: "MIT News" },
      { type: "reddit", url: "technology", name: "r/technology" },
      { type: "reddit", url: "artificial", name: "r/artificial" },
      { type: "reddit", url: "MachineLearning", name: "r/MachineLearning" },
      { type: "reddit", url: "cybersecurity", name: "r/cybersecurity" },
      { type: "reddit", url: "startups", name: "r/startups" },
      { type: "reddit", url: "gadgets", name: "r/gadgets" },
    ],
    contentPrompt: "clear, energetic, explains complex tech simply",
    voiceTone: "Informed, accessible, forward-looking",
    categorizationPrompt:
      "Focus on impact and what it means for everyday people. Categories: ai (LLMs, machine learning, AI products), startups (funding, launches, VC), cybersecurity (hacks, breaches, infosec), gadgets (hardware, devices, reviews), science (research, breakthroughs), crypto (blockchain, Web3, digital assets).",
  },

  sports: {
    id: "sports",
    name: "Sports",
    icon: "Trophy",
    description: "Football, basketball, NFL, transfers, and analysis",
    categories: [
      { id: "football", label: "Football", icon: "Circle" },
      { id: "basketball", label: "Basketball", icon: "CircleDot" },
      { id: "nfl", label: "NFL", icon: "Shield" },
      { id: "transfers", label: "Transfers", icon: "ArrowRightLeft" },
      { id: "analysis", label: "Analysis", icon: "BarChart3" },
      { id: "breaking", label: "Breaking", icon: "Zap" },
    ],
    sources: [
      { type: "rss", url: "https://feeds.bbci.co.uk/sport/rss.xml", name: "BBC Sport" },
      { type: "rss", url: "https://feeds.bbci.co.uk/sport/football/rss.xml", name: "BBC Football" },
      { type: "rss", url: "https://www.skysports.com/rss/12040", name: "Sky Sports" },
      { type: "rss", url: "https://www.skysports.com/rss/12483", name: "Sky Sports Football" },
      { type: "rss", url: "https://www.skysports.com/rss/12326", name: "Sky Sports Premier League" },
      { type: "rss", url: "https://www.theguardian.com/football/rss", name: "Guardian Football" },
      { type: "rss", url: "https://www.theguardian.com/sport/rss", name: "Guardian Sport" },
      { type: "rss", url: "https://www.espn.com/espn/rss/news", name: "ESPN" },
      { type: "rss", url: "https://www.espn.com/espn/rss/nfl/news", name: "ESPN NFL" },
      { type: "rss", url: "https://www.espn.com/espn/rss/nba/news", name: "ESPN NBA" },
      { type: "rss", url: "https://bleacherreport.com/articles/feed", name: "Bleacher Report" },
      { type: "rss", url: "https://theathletic.com/rss/", name: "The Athletic" },
      { type: "rss", url: "https://www.mirror.co.uk/sport/football/rss.xml", name: "Mirror Football" },
      { type: "rss", url: "https://www.dailymail.co.uk/sport/index.rss", name: "Daily Mail Sport" },
      { type: "reddit", url: "soccer", name: "r/soccer" },
      { type: "reddit", url: "nba", name: "r/nba" },
      { type: "reddit", url: "nfl", name: "r/nfl" },
      { type: "reddit", url: "PremierLeague", name: "r/PremierLeague" },
      { type: "reddit", url: "FantasyPL", name: "r/FantasyPL" },
      { type: "reddit", url: "formula1", name: "r/formula1" },
    ],
    contentPrompt: "passionate, energetic, stats-aware fan perspective",
    voiceTone: "Excited, opinionated, in-the-know",
    categorizationPrompt:
      "Focus on drama, upsets, records, and transfers. Categories: football (soccer), basketball (NBA, college), nfl (American football), transfers (signings, rumors, deals), analysis (tactics, stats, breakdowns), breaking (injury news, suspensions, major announcements).",
  },

  food: {
    id: "food",
    name: "Food",
    icon: "UtensilsCrossed",
    description: "Restaurants, recipes, trends, and reviews",
    categories: [
      { id: "restaurants", label: "Restaurants", icon: "Store" },
      { id: "recipes", label: "Recipes", icon: "ChefHat" },
      { id: "trends", label: "Trends", icon: "TrendingUp" },
      { id: "reviews", label: "Reviews", icon: "Star" },
      { id: "street_food", label: "Street Food", icon: "MapPin" },
      { id: "health_food", label: "Health Food", icon: "Apple" },
    ],
    sources: [
      { type: "rss", url: "https://www.theguardian.com/food/rss", name: "Guardian Food" },
      { type: "rss", url: "https://www.bbc.co.uk/food/articles.rss", name: "BBC Food" },
      { type: "rss", url: "https://www.foodnetwork.com/fn-dish/feed", name: "Food Network" },
      { type: "rss", url: "https://www.seriouseats.com/atom.xml", name: "Serious Eats" },
      { type: "rss", url: "https://www.eater.com/rss/index.xml", name: "Eater" },
      { type: "rss", url: "https://www.bonappetit.com/feed/rss", name: "Bon Appetit" },
      { type: "rss", url: "https://www.delish.com/rss/all.xml/", name: "Delish" },
      { type: "rss", url: "https://www.foodandwine.com/syndication/rss", name: "Food and Wine" },
      { type: "rss", url: "https://feeds.feedburner.com/smitten", name: "Smitten Kitchen" },
      { type: "rss", url: "https://www.thekitchn.com/main.rss", name: "The Kitchn" },
      { type: "rss", url: "https://www.bbcgoodfood.com/api/render/feed?format=rss", name: "BBC Good Food" },
      { type: "rss", url: "https://www.jamieoliver.com/feed/", name: "Jamie Oliver" },
      { type: "reddit", url: "food", name: "r/food" },
      { type: "reddit", url: "recipes", name: "r/recipes" },
      { type: "reddit", url: "Cooking", name: "r/Cooking" },
      { type: "reddit", url: "FoodPorn", name: "r/FoodPorn" },
      { type: "reddit", url: "MealPrepSunday", name: "r/MealPrepSunday" },
      { type: "reddit", url: "restaurantowners", name: "r/restaurantowners" },
    ],
    contentPrompt: "sensory, warm, makes people hungry",
    voiceTone: "Appetizing, evocative, celebratory",
    categorizationPrompt:
      "Focus on trends, viral recipes, and restaurant news. Categories: restaurants (openings, closures, industry), recipes (home cooking, techniques), trends (viral foods, fads, TikTok), reviews (restaurant reviews, product reviews), street_food (street vendors, food trucks), health_food (clean eating, diets, wellness).",
  },

  business: {
    id: "business",
    name: "Business",
    icon: "Briefcase",
    description: "Startups, markets, entrepreneurship, and personal finance",
    categories: [
      { id: "startups", label: "Startups", icon: "Rocket" },
      { id: "markets", label: "Markets", icon: "LineChart" },
      { id: "entrepreneurship", label: "Entrepreneurship", icon: "Lightbulb" },
      { id: "personal_finance", label: "Personal Finance", icon: "Wallet" },
      { id: "property", label: "Property", icon: "Home" },
      { id: "careers", label: "Careers", icon: "Users" },
    ],
    sources: [
      { type: "rss", url: "https://feeds.bbci.co.uk/news/business/rss.xml", name: "BBC Business" },
      { type: "rss", url: "https://www.theguardian.com/business/rss", name: "Guardian Business" },
      { type: "rss", url: "https://feeds.reuters.com/reuters/businessNews", name: "Reuters Business" },
      { type: "rss", url: "https://feeds.reuters.com/reuters/technologyNews", name: "Reuters Tech" },
      { type: "rss", url: "https://www.ft.com/rss/home", name: "Financial Times" },
      { type: "rss", url: "https://www.economist.com/business/rss.xml", name: "The Economist Business" },
      { type: "rss", url: "https://feeds.feedburner.com/entrepreneur/latest", name: "Entrepreneur" },
      { type: "rss", url: "https://www.forbes.com/entrepreneurs/feed/", name: "Forbes Entrepreneurs" },
      { type: "rss", url: "https://www.inc.com/rss", name: "Inc Magazine" },
      { type: "rss", url: "https://hbr.org/resources/rss/hbr-articles.xml", name: "Harvard Business Review" },
      { type: "rss", url: "https://feeds.feedburner.com/fastcompany/headlines", name: "Fast Company" },
      { type: "rss", url: "https://www.cityam.com/feed/", name: "City AM" },
      { type: "reddit", url: "entrepreneur", name: "r/entrepreneur" },
      { type: "reddit", url: "UKPersonalFinance", name: "r/UKPersonalFinance" },
      { type: "reddit", url: "smallbusiness", name: "r/smallbusiness" },
      { type: "reddit", url: "investing", name: "r/investing" },
      { type: "reddit", url: "personalfinance", name: "r/personalfinance" },
      { type: "reddit", url: "Business_Ideas", name: "r/Business_Ideas" },
    ],
    contentPrompt: "sharp, practical, actionable insights",
    voiceTone: "Authoritative, no-nonsense, opportunity-focused",
    categorizationPrompt:
      "Focus on lessons, opportunities, and warnings for entrepreneurs. Categories: startups (early-stage, funding, exits), markets (stocks, economy, macro), entrepreneurship (founder stories, advice), personal_finance (savings, investments, debt), property (real estate, housing), careers (job market, workplace).",
  },

  gaming: {
    id: "gaming",
    name: "Gaming",
    icon: "Gamepad2",
    description: "Releases, reviews, esports, and industry news",
    categories: [
      { id: "releases", label: "Releases", icon: "Calendar" },
      { id: "reviews", label: "Reviews", icon: "Star" },
      { id: "esports", label: "Esports", icon: "Trophy" },
      { id: "retro", label: "Retro", icon: "Clock" },
      { id: "industry", label: "Industry", icon: "Building2" },
      { id: "mods", label: "Mods", icon: "Wrench" },
    ],
    sources: [
      { type: "rss", url: "https://www.ign.com/rss/articles", name: "IGN" },
      { type: "rss", url: "https://www.eurogamer.net/feed", name: "Eurogamer" },
      { type: "rss", url: "https://kotaku.com/rss", name: "Kotaku" },
      { type: "rss", url: "https://www.rockpapershotgun.com/feed", name: "Rock Paper Shotgun" },
      { type: "rss", url: "https://www.pcgamer.com/rss/", name: "PC Gamer" },
      { type: "rss", url: "https://www.gamespot.com/feeds/mashup/", name: "GameSpot" },
      { type: "rss", url: "https://www.polygon.com/rss/index.xml", name: "Polygon" },
      { type: "rss", url: "https://www.gamesradar.com/rss/", name: "GamesRadar" },
      { type: "rss", url: "https://www.vg247.com/feed", name: "VG247" },
      { type: "rss", url: "https://store.steampowered.com/feeds/news/", name: "Steam News" },
      { type: "reddit", url: "gaming", name: "r/gaming" },
      { type: "reddit", url: "pcgaming", name: "r/pcgaming" },
      { type: "reddit", url: "PS5", name: "r/PS5" },
      { type: "reddit", url: "XboxSeriesX", name: "r/XboxSeriesX" },
      { type: "reddit", url: "gamedev", name: "r/gamedev" },
      { type: "reddit", url: "esports", name: "r/esports" },
      { type: "reddit", url: "patientgamers", name: "r/patientgamers" },
    ],
    contentPrompt: "enthusiastic, insider knowledge, speaks to real gamers",
    voiceTone: "Excited, opinionated, community-minded",
    categorizationPrompt:
      "Focus on controversies, releases, and industry news. Categories: releases (new games, DLC, updates), reviews (game reviews, impressions), esports (competitive gaming, tournaments), retro (retro gaming, remasters), industry (studios, acquisitions, layoffs), mods (modding, community creations).",
  },

  health: {
    id: "health",
    name: "Health",
    icon: "Heart",
    description: "Fitness, mental health, nutrition, and wellness",
    categories: [
      { id: "fitness", label: "Fitness", icon: "Dumbbell" },
      { id: "mental_health", label: "Mental Health", icon: "Brain" },
      { id: "nutrition", label: "Nutrition", icon: "Apple" },
      { id: "wellness", label: "Wellness", icon: "Sparkles" },
      { id: "medical", label: "Medical", icon: "Stethoscope" },
      { id: "research", label: "Research", icon: "FlaskConical" },
    ],
    sources: [
      { type: "rss", url: "https://feeds.bbci.co.uk/news/health/rss.xml", name: "BBC Health" },
      { type: "rss", url: "https://www.theguardian.com/society/health/rss", name: "Guardian Health" },
      { type: "rss", url: "https://www.nhs.uk/news/rss.aspx", name: "NHS News" },
      { type: "rss", url: "https://www.webmd.com/rss/rss.aspx?type=news", name: "WebMD News" },
      { type: "rss", url: "https://www.healthline.com/rss/health-news", name: "Healthline" },
      { type: "rss", url: "https://www.medicalnewstoday.com/rss/all.xml", name: "Medical News Today" },
      { type: "rss", url: "https://www.health.harvard.edu/blog/feed", name: "Harvard Health" },
      { type: "rss", url: "https://rss.sciam.com/ScientificAmerican-Global", name: "Scientific American" },
      { type: "rss", url: "https://www.menshealth.com/rss/all.xml/", name: "Mens Health" },
      { type: "rss", url: "https://www.womenshealthmag.com/rss/all.xml/", name: "Womens Health" },
      { type: "rss", url: "https://www.runnersworld.com/rss/all.xml/", name: "Runners World" },
      { type: "reddit", url: "fitness", name: "r/fitness" },
      { type: "reddit", url: "nutrition", name: "r/nutrition" },
      { type: "reddit", url: "mentalhealth", name: "r/mentalhealth" },
      { type: "reddit", url: "loseit", name: "r/loseit" },
      { type: "reddit", url: "running", name: "r/running" },
      { type: "reddit", url: "bodyweightfitness", name: "r/bodyweightfitness" },
    ],
    contentPrompt: "supportive, evidence-based, practical and actionable",
    voiceTone: "Empathetic, trustworthy, encouraging",
    categorizationPrompt:
      "Focus on new research, practical tips, and myth-busting. Categories: fitness (exercise, strength, cardio), mental_health (therapy, anxiety, depression), nutrition (diet, supplements, eating), wellness (sleep, stress, self-care), medical (conditions, treatments, doctors), research (studies, breakthroughs).",
  },
};

export const DEFAULT_GENRE = "ai" as const;

export function getGenre(id: string): Genre | undefined {
  return GENRES[id];
}

export function getAllGenres(): Genre[] {
  return Object.values(GENRES);
}
